services:
  netlab:
    image: ghcr.io/anmisttt/ddia-practice:ch9-p0
    container_name: lab-ch9-p0
    # tc/netem and iptables need these two capabilities
    cap_add:
      - NET_ADMIN
      - NET_RAW
    working_dir: /work
    volumes:
      - ./:/work
    command: ["sleep", "infinity"]
