name: ch3-n-plus-one

services:
  seed-assets:
    image: ghcr.io/anmisttt/lab:ch3-p6
    volumes:
      - postgres-init:/seed-out
    command:
      - bash
      - -c
      - cp /lab/image/postgres_seed.sql /seed-out/10-n-plus-one-seed.sql

  postgres:
    image: postgres:16-bookworm
    environment:
      POSTGRES_DB: n1_lab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-init:/docker-entrypoint-initdb.d:ro
    depends_on:
      seed-assets:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d n1_lab"]
      interval: 2s
      timeout: 3s
      retries: 30

  app:
    image: ghcr.io/anmisttt/lab:ch3-p6
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/n1_lab
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /lab
    volumes:
      - ./:/lab
    command: ["tail", "-f", "/dev/null"]
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlalchemy, psycopg"]
      interval: 2s
      timeout: 3s
      retries: 10

volumes:
  postgres-data:
  postgres-init:
