-- PostgreSQL
-- implement: denormalized rename
-- implement: lookup tables
-- implement: normalized postings table
-- implement: lookup migration
-- implement: posting migration
-- implement: lookup rename
